name: daily
on:
  push:
    branches:
      - dev
# on:
#   schedule:
#     - cron: '00 10 * * *'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 'v16.5.0'
      - name: Install dependencies & Run tests/main.js
        run: |
          npm i
          node tests/main.js
